# Generated by Django 4.0.5 on 2022-06-20 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friends_of_user', through='social.Friend', to=settings.AUTH_USER_MODEL, verbose_name='friends with'),
        ),
    ]
