# Generated by Django 4.0.5 on 2022-06-09 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0003_alter_titleperson_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='team name')),
                ('slug', models.SlugField(unique=True)),
                ('picture', models.ImageField(upload_to='teams/pictures/%Y', verbose_name='Team picture')),
                ('description', models.CharField(max_length=300, unique=True, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(default='default', upload_to='persons/pictures/%Y', verbose_name='Person picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='licensed',
            field=models.BooleanField(default=0, verbose_name='licensed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters_of_title', to='title.title'),
        ),
        migrations.AlterField(
            model_name='title',
            name='poster',
            field=models.ImageField(upload_to='titles/posters/%Y/%m', verbose_name='title poster'),
        ),
        migrations.AlterField(
            model_name='titleperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.person'),
        ),
        migrations.AlterField(
            model_name='titleperson',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons_of_title', to='title.title'),
        ),
        migrations.CreateModel(
            name='TeamParticipants',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('translator ', 'Переводчик'), ('cleaner', 'Клинер'), ('typesetter', 'Тайпер'), ('editor', 'Эдитор'), ('corrector', 'Корректор'), ('beta_reader', 'Бета читатель'), ('scanner', 'Сканер'), ('member', 'Учасник')], default='member', max_length=11)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='participants',
            field=models.ManyToManyField(related_name='teams_of_user', through='title.TeamParticipants', to=settings.AUTH_USER_MODEL, verbose_name='team participants'),
        ),
        migrations.AddField(
            model_name='team',
            name='titles',
            field=models.ManyToManyField(related_name='teams_of_title', through='title.Chapter', to='title.title', verbose_name='team titles'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters_of_team', to='title.team'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('title', 'team', 'volume', 'chapter')},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='user',
        ),
    ]
