# Generated by Django 4.0.5 on 2022-06-09 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0004_team_person_picture_title_licensed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamParticipants',
            new_name='TeamParticipant',
        ),
    ]
