# Generated by Django 4.0.5 on 2022-06-10 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0006_alter_usertitlerating_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLikes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_chapters', through='title.ChapterLikes', to=settings.AUTH_USER_MODEL, verbose_name='User likes'),
        ),
        migrations.AddField(
            model_name='chapterlikes',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='title.chapter'),
        ),
        migrations.AddField(
            model_name='chapterlikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='chapterlikes',
            unique_together={('user', 'chapter')},
        ),
    ]
