# Generated by Django 4.0.5 on 2022-06-10 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0007_chapterlikes_chapter_likes_chapter_user_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamparticipant',
            name='role',
            field=models.CharField(choices=[('translator ', 'Переводчик'), ('cleaner', 'Клинер'), ('typesetter', 'Тайпер'), ('editor', 'Эдитор'), ('corrector', 'Корректор'), ('beta_reader', 'Бета читатель'), ('scanner', 'Сканер'), ('admin', 'Админ'), ('member', 'Учасник')], default='member', max_length=11),
        ),
        migrations.AlterField(
            model_name='teamparticipant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
