# Generated by Django 4.0.5 on 2022-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0010_alter_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='picture',
            field=models.ImageField(default='', upload_to='publishers/pictures/%Y', verbose_name='Publisher picture'),
            preserve_default=False,
        ),
    ]
