# Generated by Django 4.0.5 on 2022-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0012_remove_rating_description_alter_person_picture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('-chapter_number',)},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter',
            new_name='chapter_number',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='volume',
            new_name='volume_number',
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='description'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('title', 'team', 'volume_number', 'chapter_number')},
        ),
    ]
