# Generated by Django 4.0.5 on 2022-06-11 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0013_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='volume_number',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('volume_number', 'chapter_number', 'title', 'team')},
        ),
    ]
