# Generated by Django 4.0.5 on 2022-06-11 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0014_alter_chapter_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterlikes',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='title.chapter'),
        ),
        migrations.AlterField(
            model_name='chapterlikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
