# Generated by Django 4.0.5 on 2022-06-12 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0015_alter_chapterlikes_chapter_alter_chapterlikes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterlikes',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes_for_chapter', to='title.chapter'),
        ),
    ]
