# Generated by Django 4.0.5 on 2022-06-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0016_alter_chapterlikes_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='teams',
            field=models.ManyToManyField(through='title.TitleTeam', to='title.team', verbose_name='title teams'),
        ),
        migrations.AlterField(
            model_name='team',
            name='titles',
            field=models.ManyToManyField(related_name='teams_of_title_through_chapter', through='title.Chapter', to='title.title', verbose_name='team titles'),
        ),
        migrations.AddField(
            model_name='titleteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.team'),
        ),
        migrations.AddField(
            model_name='titleteam',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_of_title', to='title.title'),
        ),
        migrations.AlterUniqueTogether(
            name='titleteam',
            unique_together={('title', 'team')},
        ),
    ]
