# Generated by Django 4.0.5 on 2022-06-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0017_titleteam_title_teams_alter_team_titles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='keyword',
            new_name='keywords',
        ),
    ]
