# Generated by Django 4.0.5 on 2022-06-15 22:06

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0018_rename_keyword_title_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alternative_names',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), size=5, verbose_name='alternative names'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='alternative_names',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200, unique=True), size=5, verbose_name='alternative names'),
        ),
    ]
