# Generated by Django 4.0.5 on 2022-06-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0019_alter_person_alternative_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitlePublisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='title.publisher')),
            ],
        ),
        migrations.RemoveField(
            model_name='title',
            name='publisher'
        ),
        migrations.AddField(
            model_name='title',
            name='publisher',
            field=models.ManyToManyField(related_name='titles_of_publisher', through='title.TitlePublisher', to='title.publisher', verbose_name='title publisher'),
        ),
        migrations.AddField(
            model_name='titlepublisher',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers_of_title', to='title.title'),
        ),
        migrations.AlterUniqueTogether(
            name='titlepublisher',
            unique_together={('title', 'publisher')},
        ),
    ]
