# Generated by Django 4.0.5 on 2022-06-16 16:16

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0022_alter_teamparticipant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamparticipant',
            name='role',
        ),
        migrations.AddField(
            model_name='teamparticipant',
            name='roles',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('translator ', 'Переводчик'), ('cleaner', 'Клинер'), ('typesetter', 'Тайпер'), ('editor', 'Эдитор'), ('corrector', 'Корректор'), ('beta_reader', 'Бета читатель'), ('scanner', 'Сканер'), ('admin', 'Админ'), ('member', 'Учасник')], default='member', max_length=11, unique=True), default=['m', 'e', 'm', 'b', 'e', 'r'], size=None),
        ),
    ]
