# Generated by Django 4.0.5 on 2022-06-16 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0024_alter_teamparticipant_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamparticipant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_participants', to='title.team'),
        ),
    ]
