# Generated by Django 4.0.5 on 2022-06-17 18:29

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0025_alter_teamparticipant_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamparticipant',
            name='roles',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(choices=[('translator', 'Переводчик'), ('cleaner', 'Клинер'), ('typesetter', 'Тайпер'), ('editor', 'Эдитор'), ('corrector', 'Корректор'), ('beta_reader', 'Бета читатель'), ('scanner', 'Сканер'), ('admin', 'Админ')], max_length=11), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='titleteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles_of_team', to='title.team'),
        ),
    ]
