# Generated by Django 4.0.5 on 2022-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0027_alter_chapter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='in_lists',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='in lists'),
        ),
    ]
