# Generated by Django 4.0.5 on 2022-06-19 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('title', '0028_title_in_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertitlerating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_ratings_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
