# Generated by Django 4.0.5 on 2022-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0029_alter_usertitlerating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title_status',
            field=models.CharField(choices=[('Announcement', 'Анонс'), ('Ongoing', 'Онгоинг'), ('Finished', 'Завершен'), ('Suspended', 'Приостановлен'), ('Stopped', 'Выпуск прекращен')], default='Announcement', max_length=12),
        ),
    ]
