# Generated by Django 4.0.5 on 2022-07-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0032_chapterimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image_archive',
            field=models.FileField(null=True, upload_to='titles/chapters'),
        ),
    ]
