# Generated by Django 4.0.5 on 2022-07-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0034_chapter_is_published_alter_chapter_image_archive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chapters_of_team', to='title.team'),
            preserve_default=False,
        ),
    ]
