# Generated by Django 4.0.5 on 2022-06-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0017_titleteam_title_teams_alter_team_titles_and_more'),
        ('social', '0006_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=30, verbose_name='list name'),
        ),
        migrations.AlterUniqueTogether(
            name='listtitle',
            unique_together={('list', 'title')},
        ),
    ]
