# Generated by Django 4.0.5 on 2022-06-17 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_list_name_alter_listtitle_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='list name'),
        ),
    ]
