# Generated by Django 4.0.5 on 2022-06-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0026_alter_teamparticipant_roles_alter_titleteam_team'),
        ('social', '0008_alter_list_hidden_alter_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=30, verbose_name='list name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_subscriptions', to='title.title'),
        ),
    ]
