# Generated by Django 4.0.5 on 2022-06-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_add_date_listtitle_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
