# Generated by Django 4.0.5 on 2022-06-20 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0029_alter_usertitlerating_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0012_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtitle',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.list'),
        ),
        migrations.AlterField(
            model_name='listtitle',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists_of_title', to='title.title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
