# Generated by Django 4.0.5 on 2022-06-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_alter_listtitle_list_alter_listtitle_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ('id',)},
        ),
    ]
