# Generated by Django 4.0.5 on 2022-06-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_comment_votes_alter_commentvote_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
    ]
