# Generated by Django 4.0.5 on 2022-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_alter_comment_comment_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_chapter', 'Вышла новая глава'), ('status_changed', 'У тайтла изменился статус'), ('friend_request', 'Новый апрос в друзья'), ('friend_accepted', 'Пользователь подтвердил ваш запрос на дружбу'), ('join_team_request', 'Вас пригласили вступить в команду переводчиков'), ('team_kick', 'Вас исключили из команды переводчиков'), ('comment_reply', 'Пользователь дал ответ на ваш комментарий'), ('chapter_success', 'Глава была успешно загружена'), ('chapter_fail', 'Возникла ошибка при загрузке главы')], max_length=20),
        ),
    ]
