# Generated by Django 4.0.5 on 2022-07-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Вышла новая глава'), (2, 'У тайтла изменился статус'), (3, 'Новый запрос в друзья'), (4, 'Пользователь подтвердил ваш запрос на дружбу'), (5, 'Вас пригласили вступить в команду переводчиков'), (6, 'Вас исключили из команды переводчиков'), (7, 'Пользователь дал ответ на ваш комментарий'), (8, 'Глава была успешно загружена'), (9, 'Возникла ошибка при загрузке главы'), (10, 'Глава была успешно обновлена'), (11, 'Возникла ошибка при обновлении главы')]),
        ),
    ]
