# Generated by Django 4.0.5 on 2022-07-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_alter_notification_id_alter_notification_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('user', 'title'), name='social_subscription_user_title_unique'),
        ),
    ]
